baseURL = "/"
languageCode = "en-us"
title = "Social Justice, Minus Dogma Online Course + Community"

[params]
	description = "A six-week online course + community charting a path toward equity. Started by Sam Killermann. Led by you."
	images = ["img/og-image.jpg"]
