baseURL = "/"
languageCode = "en-us"
title = "Social Justice, Minus Dogma Online Course + Community"

[params]
	description = "Facilitated by Sam Killermann, charting a path toward equity."
	images = ["img/og-image.jpg"]
